### ISSUE TITLE
[FEATURE] Anything to anything routing

### ISSUE THREAD

**Issue by magnetophon** [Chowdhury-DSP/BYOD#14]
@jatinchowdhury18 You already mentioned wanting to implement parallel processing [here](https://github.com/Chowdhury-DSP/BYOD/issues/8#issuecomment-891504824).

Great!  :)

If I may dream out loud: I'd love anything to anything routing, like in Ardour.
Even better would be to include @x42's full latency compensation.
I don't expect this to happen anytime soon, or at all, but wanted to mention it anyway.

Thanks!

**Comment by jatinchowdhury18** [comment]
That's a good point, maybe rather than thinking about parallel processing, the end goal should be to go for "truly flexible" routing. Actually, (for some reason) thinking about it this way makes it seem easier in my head.

Since the goal is to be a guitar pedal-style effect, ideally all of the processors should be zero-latency, so no latency compensation should be necessary. If a processor comes along that really needs latency, then maybe I'll have to think about it a little bit more...

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Wasn't sure when to close this issue, since it's was a work in progress for a long while, but I think it's fair to say that anything-to-anything routing is now fully functional!
