### ISSUE TITLE
[BUG] Version and tags

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/BYOD#241]
**Describe the bug**
It's not quite a bug. BYOD itself is 1.0.10 (at now), but git tag is still 1.0.1.
This confuses a bit when I build it and package version is relayed on tag+commit. Does it make a sense to align version and tag, or tags are for stable releases only?

**Comment by jatinchowdhury18** [comment]
Hi Konstantin! I've been bumping up the version recently for two reasons:
1. To let beta testers and Nightly build users know that we're getting close to version 1.1.0
2. Since the App Store requires a new version number for every test build for iOS beta testers

In general, I only create a new git tag when a new stable release is ready, but I may decide to increment the plugin version at other times, usually for the benefit of beta testers.

**Comment by KottV** [comment]
Hi!

I see now, thanks. No need to change any here, I can reconsider how my build macros works:)
