### ISSUE TITLE
[BUG] Very high CPU useage with Metal Face module

### ISSUE THREAD

**Issue by Prefader** [Chowdhury-DSP/BYOD#259]
**Describe the bug**
Running v1.1.3 on debian bullseye 64 bit, standalone or vst versions of BYOD,  loading the "Metal Face" module loads the cpu to 100%. Lowering the sample rate or raising the buffer size cause the cpu useage to climb slower, but it still reaches 100% at all sample rate and buffer sizes.

**To Reproduce**
1. start an empty canvas and load the Metal Face module
2. route signal in and out of the module
3. turn the module on.
4. CPU climbs to 100%, xruns ensue.

 - OS: Debian Bullseye , kernel 5.10.0-21-amd64 (also tested with 5.10.0-21-rt-amd64)
 - DAW: Bitwig Studio & standalone plugin (tested with both jack and alsa)
 - Version: 1.1.3
 
**Additional context**
built from source, clap & opengl disabled.

**Comment by jatinchowdhury18** [comment]
Hi there!

If you're building from source and looking to make a fully-optimized build (I'm assuming you want a fully-optimized build since you're asking about CPU usage), I'd first suggest double checking your configure/build flags. Specifically, you'll probably want to use the build commands in the second "snippet" from the [Building](https://github.com/Chowdhury-DSP/BYOD#building) section of the README.

Beyond that, the Metal Face module relies pretty heavily on certain SIMD intrinsics, so depending on your system's support for those instructions, I imagine that could have a significant impact on the plugin's CPU usage. Other modules use SIMD as well, so I imagine you would probably run into a similar issue with those models.

And beyond that, the Metal Face module is generally expected to be one of the more CPU-heavy modules in the plugin, just by nature of the algorithms that it's using. That said, I've heard of folks running similar algorithms on a Raspberry Pi, so I imagine on most modern CPUs we should be able to get the CPU usage well below 100%.

**Comment by Prefader** [comment]
Thanks for taking the time to reply. I apologize for not including details about the build flags I used.

Indeed, I forgot to try building optimized; freshly built with the correct flags, the Metal Face device uses significantly less CPU.

Reading is, still, fundamental.

Again, thank you for your time and these beautiful plugins.
