### ISSUE TITLE
[FEATURE] Setting to automatically set up connections when there is only one active processor left.

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#301]
After adding / removing processors and there's only one active processor left and said option is on, BYOD would automatically connect the necessary cables.

**Comment by jatinchowdhury18** [comment]
I think I'd rather not do this, since in my experience most of the time when there's only one processor on the "board", it's either because:
- I'm just starting to set up a new patch, in which case I'd likely have to delete one or both of the automatically added cables to continue building the patch
- I'm trying to delete all the processors on the board, in which case it doesn't matter if those cables get automatically added, since they're about to get deleted when I delete the last processor anyway.

Besides, for the use case where the user actually only want to use one processor, it's possible to get there from the "default" patch with one click (for "one-to-one" processors), by replacing the cable with a processor.

I think adding this kind of behaviour would also make some of the undo/redo behaviour confusing... if some cables are added automatically, would an undo or redo action be expected to automatically add/remove those cables as well. I imagine the implementation for that would be difficult.
