### ISSUE TITLE
[FEATURE] Cable connection handling quality of life.

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#304]
Currently, cable connections are completely removed as soon as the user clicks on a cable (mouse-down). I believe it would be more user friendly if instead mouse-down engaged cable-dragging and a check ran on mouse-up:

- If there is no connector near the pointer, destroy the cable.
- If the connector near the pointer hasn't changed and very little time has passed, destroy the cable.
- If the connector near the pointer hasn't changed, but a considerable amount of time has passed between mouse-down and mouse-up, or the pointer has travelled a considerable distance, keep the existing connection.
- If the connector near the pointer has changed, connect the cable to the new connector.

**Comment by jatinchowdhury18** [comment]
So we actually had implemented this sort of functionality (minus the 3rd point on your list) when we first started implementing the draggable cables in BYOD (there was another way of doing routing before that, but it was a lot less flexible, hence the switch over to cables). We ended up moving to the current behaviour (mouse-down on a connected port destroys the cable), since it became a bit difficult to destroy a cable when working in a somewhat crowded pedalboard. We ran a little informal poll among folks who were beta-testing BYOD at the time, and the current functionality won out.
