### ISSUE TITLE
[FEATURE] Selective oversampling

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#305]
Maybe processors should have a  'do not want oversampling' setting (that can be toggled by the user?). BYOD would then determine the longest possible chain from 'In' and the longest possible chain from 'Out' for which oversampling can be disengaged. 

Oversampling toggled off for IR and reverb:

Chain: In -> IR -> Verb -> IR -> Out.
Oversampled: -

Chain: In -> IR -> Drive -> IR -> Verb -> Out
Oversampled: Drive

Chain: In -> IR -> Verb -> Drive -> IR -> Drive -> IR -> Verb -> Out
Oversampled: Drive -> IR -> Drive

**Comment by jatinchowdhury18** [comment]
We've considered doing something like this in the past, and have chosen not to for three reasons:
1. In cases where the signal chain would require multiple up/down-sampling stages, the latency incurred by each stage would add cumulatively. If many such stages are required, the total latency could end up being quite large, which is not ideal as BYOD is intended to be usable in live performance situations.
2. Since BYOD supports non-serial audio graphs, there could be multiple parallel "chains" of processors that have different amounts of latency. When the chains are later combined together again, there would need to be some form of latency compensation to make sure that the signals being combined are in-phase with each other. BYOD's audio-graph currently does not support latency compensation.
3. When considering the CPU and RAM cost of having potentially many up/down-sampling stages, it's likely that in many situations, being able to run certain processors without oversampling wouldn't actually improve the plugin's performance.

Because BYOD operates in this way, we also try to discourage users from going to crazy with BYOD's impulse response modules (see #246).
