### ISSUE TITLE
[FEATURE] make the tuner a separate plugin too

### ISSUE THREAD

**Issue by RustoMCSpit** [Chowdhury-DSP/BYOD#359]
**Describe the solution you'd like**
the tuner is useful and id like to use it separately

**Comment by jatinchowdhury18** [comment]
I've generally been hesitant to create individual plugins for any of the BYOD modules, mainly because the argument could be made that every single module in BYOD could be its own plugin, and the maintenance burden for 50+ plugins would be very high. 

With the current version of the plugin, it takes ~3 clicks from creating an instance of the plugin to having the tuner up and running (2 clicks if you were to create a tuner preset). I'm not sure that I can justify the effort of creating an entirely separate plugin just to save the user 3 clicks.

**Comment by RustoMCSpit** [comment]
> With the current version of the plugin, it takes ~3 clicks from creating an instance of the plugin to having the tuner up and running (2 clicks if you were to create a tuner preset). I'm not sure that I can justify the effort of creating an entirely separate plugin just to save the user 3 clicks.

i mean, if youre willing to reconsider. maybe just make it a once off you never update.
