### ISSUE TITLE
[FEATURE] an input / output module. 

### ISSUE THREAD

**Issue by RustoMCSpit** [Chowdhury-DSP/BYOD#362]
**Describe the solution you'd like**
id like to create more than one input and output so having it as a module would be great. id like to be able to pan it, set gain, etc.. that way i can have two or more signal chains going left and right

**Comment by jatinchowdhury18** [comment]
The idea with the input/output modules is that they correspond with the plugin inputs/outputs in the DAW. Since the plugin only has 1 input and 1 output bus from the perspective of the DAW, I'm not sure it makes sense to have multiple input/output modules on the pedalboard.

Besides, since it's possible to have multiple "wires" coming out of the Input module, I'm not sure we would logically get anything new from being able to have multiple input modules. For having multiple outputs, the outputs would all need to be "mixed" together into the plugin's output bus to be sent back to the DAW, so you might as well do that with the Mixer module. For being able to set gain or panning for the different inputs/outputs that's already possible using the Gain, Panner, and Mixer modules. I guess it's possible that having multiple input/output modules would result in _slightly_ less "clutter" on the pedalboard, but I'm not sure that would be enough of a justification for this kind of change.

**Comment by RustoMCSpit** [comment]
>  I'm not sure we would logically get anything new from being able to have multiple input modules 

sidechaining?
