### ISSUE TITLE
[BUG] GUI laggy in current version (0.2.0)

### ISSUE THREAD

**Issue by IsaakCode** [Chowdhury-DSP/BYOD#59]
**Describe the bug**
Dragging notes and modules is very laggy in the early version on my computer setup, despite the simplicity of the visual elements. I'm sure the issue will be adressed in future versions, so this is just meant as a heads up notice. I experience the issue on an older Windows machine without graphical hardware acceleration (see below). 

**To Reproduce**
1. Add a module
2. drag a note

**Expected behavior**
Moving and dragging elements without considerable lag. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - DAW Ableton Live 11
 - Version 0.2.0
 - 64 bit VST3
 - Third generation Intel i5 desktop processor
 - 8 gb of RAM
 - Intel HD Graphics 2000 (integrated)
 - 1920 x 1080 resolution

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! Unfortunately, I haven't been able to reproduce this behaviour on my Windows machine; even on "Debug" builds, the UI movements aren't noticeably laggy.

I wonder if this may be an issue with OpenGL, since the plugin is compiled with OpenGL on by default when building for Windows and Linux. I was thinking it might be good to make this an option, so the user can choose whether OpenGL is on or off from the plugin settings menu. Once I get that implemented, it might be worthwhile to do another test and see what happens!

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Cool, so the latest nightly build has an option for enabling/disabling OpenGL of you'd like to test with that.

**Comment by IsaakCode** [comment]
Indeed, with OpenGL disabled the lag is gone and the GUI interaction works as expected without graphical latency. Turning OpenGL on causes the lag issue again. So I guess the option to enable and disable OpenGL is really helpful to increase compatibility with older (integrated) graphics chips.

**Comment by jatinchowdhury18** [comment]
Awesome! In that case, I'll leave everything as it currently is, where OpenGL is off by default, but users can enable it if they want to.

Thanks!
